export const STRINGS = {
    NO_AVAILABLE_DATA: 'No available data',
    ACCOUNT: 'Account',
    FEED: 'Feed',
    WALLET: 'Wallet',
    PLANS: 'Plans',
    HOME: 'Home',
    PHONE_NUMBER: 'Phone Number',
    ERROR_OCCURRED: 'An error has occurred, please try again',
    WELCOME_BACK: 'Welcome back',
    LETS_GET_YOU_LOGGED_IN: 'Let’s get you logged in to get back to building your dollar-denominated investment portfolio.',
    EMAIL_ADDRESS: 'Email address',
    PASSWORD: 'Password',
    SIGN_IN: 'Sign In',
    FORGOT_PASSWORD: 'I forgot my password',
    DONT_HAVE_ACCOUNT: "Don't have an account?",
    SIGNUP: 'Sign up',
    OKAY: 'Okay',
    WELCOME_TO_RISE: 'Welcome to Rise, let’s take you home',
    YOU_CREATED_ACCOUNT: 'You just created your Rise account',
    CREATE_ACCOUNT: 'Create an account',
    START_BUILDING_YOUR_PORTFOLIO: 'Start building your dollar-denominated investment portfolio',
    TELL_US_MORE: 'Tell Us More About You',
    USE_NAME_AS_ON_ID: 'Please use your name as it appears on your ID.',
    NEXT: 'Next',
    QUALITY_ASSETS: 'Quality assets',
    SUPERIOR_SELECTION: 'Superior Selection',
    BETTER_PERFORMANCE: 'Better Performance',
    SLIDER_TEXT_1: 'Rise invests your money into the best dollar investments around the world.',
    SLIDER_TEXT_2: 'Our expert team and intelligent algorithms select assets that beat the markets.',
    SLIDER_TEXT_3: 'You earn more returns, achieve more of your financial goals and protect your money from devaluation.',
    CONTINUE: 'Continue',
    FIRST_NAME: 'Legal First Name',
    LAST_NAME: 'Legal Last Name',
    NICK_NAME: 'Nick name',
    GOAL_NAME: 'Goal name',
    QUESTION1: 'Question 1 of 3',
    QUESTION2: 'Question 2 of 3',
    QUESTION3: 'Question 3 of 3',
    WHAT_ARE_YOU_SAVING_FOR: 'What are you saving for',
    TARGET_AMOUNT: 'Target amount',
    HOW_MUCH_DO_YOU_NEED: 'How much do need?',
    TARGET_DATE: 'Target date',
    WHEN_TO_WITHDRAW: 'When do you want to withdraw?',
    CHOOSE_A_DATE: 'Choose a date',
    VIEW_PLAN: 'View plan',
    REVIEW: 'Review',
    NAIRA_SYMBOL: '₦',
    FUND_WALLET: 'Fund Wallet',
    MINIMUM_CHARACTERS: 'Minimum of 8 characters',
    ONE_UPPER_CASE: 'One UPPERCASE character',
    ONE_UNIQUE_CHARACTER: 'One unique character (e.g: !@#$%^&*?)',
    DATE_OF_BIRTH: 'Date of Birth',
    BY_CLICKING_CONTINUE: 'By clicking Continue, you agree to our',
    TERMS_OF_SERVICE: 'Terms of Service',
    PRIVACY_POLICY: 'Privacy Policy.',
    AND: 'and',
    TOTAL_BALANCE: 'Total Balance',
    TOTAL_GAINS: 'Total Gains',
    CREATE_INVESTMENT_PLAN: 'Create an investment plan',
    ADD_MONEY: 'Add money',
    CREATE_A_PLAN: 'Create a plan',
    VIEW_ALL_PLANS: 'View all plans',
    START_YOUR_INVESTMENT_JOURNEY: 'Start your investment journey by creating a plan',
    NEED_HELP: 'Need help?',
    CONTACT_US: 'Contact us',
    TODAYS_QUOTE: 'TODAY’S QUOTE',
    ABOUT_EXCHANGE_RATES: 'About Exchange Rates',
    USD_BUY_RATE: 'USD Buy Rate',
    WE_BUY_USD: 'We buy US dollars at this rate',
    USD_SELL_RATE: 'USD sell Rate',
    CURRENT_VALUE_IN_NAIRA: 'The current value of your investments in Naira',
    THESE_EXCHANGE_RATES_ARE_PROVIDED_BY_THIRD_PARTIES: 'These exhange rates are provided by independent third parties who handle fund conversions at the prevailing parallel rates and are not set, or controlled or by Rise. They are subject to change based on market trends.',
    ACCEPT_AND_CONTINUE: 'Accept & Continue',
    YOU_JUST_CREATED_YOUR_PLAN: 'You just created your plan.',
    WELDONE: 'Well done, ',
    REACH_YOUR_GOALS_FASTER: 'Reach your goals faster'
}